[package]
name = "tcp-v4-connect-user"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = { git = "https://github.com/aya-rs/aya" }
anyhow = "1"
env_logger = "0.10"
libc = "0.2"
log = "0.4"

[[bin]]
name = "tcp-v4-connect-user"
path = "src/main.rs"
